### ISSUE TITLE
 bug(mock!): Error E0412, Cannot find type K in this scope when using mock! macro

### ISSUE THREAD

**Issue by gate2017aloy** [asomers/mockall#630]
I encountered an issue while using the mockall library to create a mock implementation for store operations in my Rust project. The error message I received is: `error[E0412]: cannot find type `K` in this scope`

`mock! {
    /// Mock implementation for store operations used in testing.
    pub StoreSetProto<T: Default + prost::Message + 'static> {}

    impl<T: prost::Message + 'static + Default> StoreNew for StoreSetProto<T> {
        fn new() -> Self;
    }

    impl<T: prost::Message + 'static + Default> StoreDelete for StoreSetProto<T> {
        #[cfg_attr(concretize)]
        fn delete_prefix(&self, ordinal: i64, key: &String);
    }

    impl<T: Default + prost::Message + 'static> StoreSet<T> for StoreSetProto<T> {
        #[cfg_attr(concretize)]
        fn set<K: AsRef<str>>(&self, ord: u64, key: K, value: &T);

        #[cfg_attr(concretize)]
        fn set_many<K: AsRef<str>>(&self, ord: u64, keys: &Vec<K>, value: &T);
    }
}`

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the mock implementation to include the generic parameter K in StoreSetProto and adjusted the trait implementations accordingly. This should resolve the 'cannot find type `K` in this scope' error.

You can review changes in this commit: https://github.com/kkpo4553/asomers-mockall-630/commit/34fa91e83dbb58cfdfba8573714c4ca180fb191e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by gate2017aloy** [comment]
> @gate2017aloy could you please provide some more information? A minimal example to reproduce the problem would be great. The example you provided can't even compile, because it doesn't include definitions for the StoreNew, StoreSet, and StoreDelete traits. Also, which section of code is triggering that error? The compiler should tell you.

Hi @asomers 

We are trying to mock `StoreSetProto` of `substreams::store`

You can refer to the dependencies below

- substreams = "0.5.22"
- substreams-ethereum = "0.9.13"
- mockall = "0.13.0"
- prost = '^0.11.0'
- prost-types = '0.11.0'
- pretty_assertions = "1.4.1"

The compile time error is seen in the `set_many` method when mocking the `StoreSet` trait for `StoreSetProto`

```
    impl<T: Default + prost::Message + 'static> StoreSet<T> for StoreSetProto<T> {
        #[cfg_attr(concretize)]
        fn set<K: AsRef<str>>(&self, ord: u64, key: K, value: &T);

        #[cfg_attr(concretize)]
        fn set_many<K: AsRef<str>>(&self, ord: u64, keys: &Vec<K>, value: &T);
    }

```

The error as mentioned above `error[E0412]: cannot find type K in this scope`

**Comment by asomers** [comment]
That's still not a complete example.  If you think that Mockall has a bug, could you please provide a _minimal_ example?  That is, a self-contained example that doesn't rely on external crates and does not contain methods irrelevant to the issue at hand?
